1.	Handle missing values as per the best practices (imputation, removal, etc.).
●	Apply scaling techniques to numerical features:
a.	Standard Scaling   b. Min-Max Scaling
●	Discuss the scenarios where each scaling technique is preferred and why.

In [73]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import seaborn as sns

In [74]:
df = pd.read_csv('adult_with_headers (1).csv')

In [76]:
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [78]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

There is no null values

In [80]:
target = df['income']
features = df.drop(columns=['income'])
features.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba

In [81]:
## Scaling
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [82]:
std_sca = StandardScaler()
min_ma = MinMaxScaler()

In [83]:
## Standard Scaling
std_sca.fit_transform(features[['age','fnlwgt','education_num','capital_gain','capital_loss','hours_per_week']])
## Min-Max scaling
min_ma.fit_transform(features[['age','fnlwgt','education_num','capital_gain','capital_loss','hours_per_week']])

array([[0.30136986, 0.0443019 , 0.8       , 0.02174022, 0.        ,
        0.39795918],
       [0.45205479, 0.0482376 , 0.8       , 0.        , 0.        ,
        0.12244898],
       [0.28767123, 0.13811345, 0.53333333, 0.        , 0.        ,
        0.39795918],
       ...,
       [0.56164384, 0.09482688, 0.53333333, 0.        , 0.        ,
        0.39795918],
       [0.06849315, 0.12849934, 0.53333333, 0.        , 0.        ,
        0.19387755],
       [0.47945205, 0.18720338, 0.53333333, 0.1502415 , 0.        ,
        0.39795918]], shape=(32561, 6))

a) Standard Scaler
- If the data is normall distributed and you can use standard scler.This technique is commonly used one
- But this technique is sensitive to outliers
b) Min-Max Scaler
- This technique use when data does not follow normal distribution
- This also used when we dont want negative values.
- This technique is also sensitive to outliers
c) Robust Scaler
- This techniques used when data contains many outliers and distribution is skewed
- This is more stable scaling technique

2. Encoding Techniques:
●	Apply One-Hot Encoding to categorical variables with less than 5 categories.
●	Use Label Encoding for categorical variables. Data Exploration and Preprocessing:
●	Load the dataset and conduct basic data exploration (summary statistics, missing values, data types).
●	les with more than 5 categories.
●	Discuss the pros and cons of One-Hot Encoding and Label Encoding.

In [84]:
features.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba

In [85]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
dtypes: int64(6), object(8)
memory usage: 3.5+ MB

In [86]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [87]:
one_hot = OneHotEncoder() ## OnehotEncoder is used for Nominal columns
lab_en = LabelEncoder() ## LabelEncoder is used for ordinal columns

In [88]:
## OnehotEncoder
features = pd.get_dummies(features,columns=['marital_status','sex','race'],dtype='int')
features.head()

,age,workclass,fnlwgt,education,education_num,occupation,relationship,capital_gain,capital_loss,hours_per_week,...,marital_status_ Never-married,marital_status_ Separated,marital_status_ Widowed,sex_ Female,sex_ Male,race_ Amer-Indian-Eskimo,race_ Asian-Pac-Islander,race_ Black,race_ Other,race_ White
0,39,State-gov,77516,Bachelors,13,Adm-clerical,Not-in-family,2174,0,40,...,1,0,0,0,1,0,0,0,0,1
1,50,Self-emp-not-inc,83311,Bachelors,13,Exec-managerial,Husband,0,0,13,...,0,0,0,0,1,0,0,0,0,1
2,38,Private,215646,HS-grad,9,Handlers-cleaners,Not-in-family,0,0,40,...,0,0,0,0,1,0,0,0,0,1
3,53,Private,234721,11th,7,Handlers-cleaners,Husband,0,0,40,...,0,0,0,0,1,0,0,1,0,0
4,28,Private,338409,Bachelors,13,Prof-specialty,Wife,0,0,40,...,0,0,0,1,0,0,0,1,0,0

In [89]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 25 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   age                                    32561 non-null  int64
 1   workclass                              32561 non-null  object
 2   fnlwgt                                 32561 non-null  int64
 3   education                              32561 non-null  object
 4   education_num                          32561 non-null  int64
 5   occupation                             32561 non-null  object
 6   relationship                           32561 non-null  object
 7   capital_gain                           32561 non-null  int64
 8   capital_loss                           32561 non-null  int64
 9   hours_per_week                         32561 non-null  int64
 10  native_country                         32561 non-null  object
 11  marital_status_ Divorced               32561 non-null  int64
 12  marital_status_ Married-AF-spouse      32561 non-null  int64
 13  marital_status_ Married-civ-spouse     32561 non-null  int64
 14  marital_status_ Married-spouse-absent  32561 non-null  int64
 15  marital_status_ Never-married          32561 non-null  int64
 16  marital_status_ Separated              32561 non-null  int64
 17  marital_status_ Widowed                32561 non-null  int64
 18  sex_ Female                            32561 non-null  int64
 19  sex_ Male                              32561 non-null  int64
 20  race_ Amer-Indian-Eskimo               32561 non-null  int64
 21  race_ Asian-Pac-Islander               32561 non-null  int64
 22  race_ Black                            32561 non-null  int64
 23  race_ Other                            32561 non-null  int64
 24  race_ White                            32561 non-null  int64
dtypes: int64(20), object(5)
memory usage: 6.2+ MB

In [90]:
features['education'].unique()

array([' Bachelors', ' HS-grad', ' 11th', ' Masters', ' 9th',
       ' Some-college', ' Assoc-acdm', ' Assoc-voc', ' 7th-8th',
       ' Doctorate', ' Prof-school', ' 5th-6th', ' 10th', ' 1st-4th',
       ' Preschool', ' 12th'], dtype=object)

In [91]:
## label encoder
features['education'] = lab_en.fit_transform(features['education'])
features.head()

,age,workclass,fnlwgt,education,education_num,occupation,relationship,capital_gain,capital_loss,hours_per_week,...,marital_status_ Never-married,marital_status_ Separated,marital_status_ Widowed,sex_ Female,sex_ Male,race_ Amer-Indian-Eskimo,race_ Asian-Pac-Islander,race_ Black,race_ Other,race_ White
0,39,State-gov,77516,9,13,Adm-clerical,Not-in-family,2174,0,40,...,1,0,0,0,1,0,0,0,0,1
1,50,Self-emp-not-inc,83311,9,13,Exec-managerial,Husband,0,0,13,...,0,0,0,0,1,0,0,0,0,1
2,38,Private,215646,11,9,Handlers-cleaners,Not-in-family,0,0,40,...,0,0,0,0,1,0,0,0,0,1
3,53,Private,234721,1,7,Handlers-cleaners,Husband,0,0,40,...,0,0,0,0,1,0,0,1,0,0
4,28,Private,338409,9,13,Prof-specialty,Wife,0,0,40,...,0,0,0,1,0,0,0,1,0,0

In [92]:
## summary statistics
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [93]:
## Missing Values
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [94]:
## data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

1. OneHotEncoder
Pros
- No false relationship between categories, each category is independent
- Works well with linear models
- Easy to understand
Cons
- Creates many columns based on the values in the columns.
- Memory inefficient, large dataset become heavy
- Can reduce model performance
2. LabelEncoder
Pros
- Simple and fast, converts categories into numbers easily
- No increase in number of columns, keep dataset compact
- Efficient for large datasets, works well when categories is many
Cons
- Not suitable for linear models
- Can reduce model accuracy
- Introduces false order

3. Feature Engineering:
●	Create at least 2 new features that could be beneficial for the model. Explain the rationale behind your choices.
●	Apply a transformation (e.g., log transformation) to at least one skewed numerical feature and justify your choice.

In [95]:
target = df['income']
features = df.drop(columns=['income'])

In [96]:
features.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba

In [97]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
dtypes: int64(6), object(8)
memory usage: 3.5+ MB

In [65]:
## We can add new features income_per_hour and age_group
df['income_per_hour'] = (df['capital_gain'] - df['capital_loss']) / (df['hours_per_week'] + 1)
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,income_per_hour
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,53.02439
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,0.00000
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,0.00000
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,0.00000
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,0.00000

In [66]:
def age_group(age):
    if age < 25:
        return 'Young'
    elif age < 45:
        return 'Adult'
    elif age < 65:
        return 'Middle_Age'
    else:
        return 'Senior'

df['age_group'] = df['age'].apply(age_group)

In [67]:
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,income_per_hour,age_group
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,53.02439,Adult
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,0.00000,Middle_Age
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,0.00000,Adult
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,0.00000,Middle_Age
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,0.00000,Adult

Income_per_hour :-
- This feature combines capital gain, capital loss, and working hours to estimate earning efficiency. It may better capture financial status compared to using these variables independently.
Age_Group
- Age is grouped into categories to capture different life stages, which may have different income patterns. This simplifies the model's ability to detect trends.

In [69]:
df.skew(numeric_only=True)

age                 0.558743
fnlwgt              1.446980
education_num      -0.311676
capital_gain       11.953848
capital_loss        4.594629
hours_per_week      0.227643
income_per_hour    15.691634
dtype: float64

In [72]:
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,income_per_hour,age_group
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,7.684784,0,40,United-States,<=50K,3.989436,Adult
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.000000,0,13,United-States,<=50K,0.000000,Middle_Age
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.000000,0,40,United-States,<=50K,0.000000,Adult
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.000000,0,40,United-States,<=50K,0.000000,Middle_Age
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.000000,0,40,Cuba,<=50K,0.000000,Adult

In [70]:
## apply log transformation on income_per_hour and capital_gain
df['capital_gain'] = np.log1p(df['capital_gain'])
df['income_per_hour'] = np.log1p(df['income_per_hour'])

In [71]:
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,income_per_hour,age_group
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,7.684784,0,40,United-States,<=50K,3.989436,Adult
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.000000,0,13,United-States,<=50K,0.000000,Middle_Age
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.000000,0,40,United-States,<=50K,0.000000,Adult
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.000000,0,40,United-States,<=50K,0.000000,Middle_Age
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.000000,0,40,Cuba,<=50K,0.000000,Adult

- Skewness of numerical features was analyzed using the .skew() function. The income_per_hour and capital_gain features showed a high positive skew, indicating the presence of extreme values.
- A log transformation was applied to the income_per_hour and capital_gain features using log1p() to reduce skewness. This helps stabilize variance and improves model performance by making the distribution more normal.